# Generated by Django 5.0.1 on 2024-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='1cd91e0569c248df', max_length=32, unique=True),
        ),
    ]
