# Generated by Django 5.0.1 on 2024-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_ride_pickup_latitude_ride_pickup_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='222f0003e36448f0', max_length=32, unique=True),
        ),
    ]
