# Generated by Django 5.0.1 on 2024-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_ride_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='3f11572e0f7c4f79', max_length=32, unique=True),
        ),
    ]
