# Generated by Django 5.0.1 on 2024-04-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_ride_driver1_alter_ride_token'),
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver1',
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='23b6014b3b6545b0', max_length=32, unique=True),
        ),
    ]
