# Generated by Django 5.0.1 on 2025-09-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.CharField(blank=True, max_length=500, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_for_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('matching', 'Matching'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('on_trip', 'On Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('estimate_distance_m', models.IntegerField(blank=True, null=True)),
                ('estimate_duration_s', models.IntegerField(blank=True, null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='verify.drivers')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='verify.users')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='verify.drivers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='verify.users')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.ride')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='main.ride')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(blank=True, max_length=30, null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verify.users')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.ride')),
            ],
            options={
                'db_table': 'ride_events',
            },
        ),
        migrations.CreateModel(
            name='DriverAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, help_text='sha256 hash of the token (raw token not stored).', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='verify.drivers')),
            ],
            options={
                'db_table': 'driver_api_key',
                'indexes': [models.Index(fields=['driver'], name='driver_api__driver__c4adfb_idx'), models.Index(fields=['-last_used'], name='driver_api__last_us_9ce0d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('web', 'web')], default='android', max_length=20)),
                ('push_token', models.CharField(max_length=500)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='verify.drivers')),
            ],
            options={
                'db_table': 'driver_devices',
                'indexes': [models.Index(fields=['driver'], name='driver_devi_driver__d39807_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='verify.drivers')),
            ],
            options={
                'db_table': 'driver_live',
                'indexes': [models.Index(fields=['is_online'], name='driver_live_is_onli_d27c11_idx'), models.Index(fields=['-last_seen'], name='driver_live_last_se_8b84fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='verify.drivers')),
            ],
            options={
                'db_table': 'driver_locations',
                'indexes': [models.Index(fields=['driver', '-recorded_at'], name='driver_loca_driver__a7d95d_idx'), models.Index(fields=['recorded_at'], name='driver_loca_recorde_dfc965_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user', '-created_at'], name='rides_user_id_71f6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_status_3bc8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['driver'], name='reviews_driver__4f2e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='reviews_user_id_79db63_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['ride', '-created_at'], name='ride_events_ride_id_a4aba4_idx'),
        ),
    ]
